In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.svm import SVC

In [2]:
df=pd.read_csv(r"C:\Users\shash\OneDrive\Desktop\mit\3rd sem\ml\OneDrive_1_15-8-2023\DATASETS-16AUG2023\Mushroom.csv")


In [3]:
df


cap-shape cap-surface cap-color bruises odor gill-attachment  \
0            x           s         n       t    p               f   
1            x           s         y       t    a               f   
2            b           s         w       t    l               f   
3            x           y         w       t    p               f   
4            x           s         g       f    n               f   
...        ...         ...       ...     ...  ...             ...   
8119         k           s         n       f    n               a   
8120         x           s         n       f    n               a   
8121         f           s         n       f    n               a   
8122         k           y         n       f    y               f   
8123         x           s         n       f    n               a   

     gill-spacing gill-size gill-color stalk-shape  ...  \
0               c         n          k           e  ...   
1               c         b          k           e  ...   
2               c         b          n           e  ...   
3               c         n          n           e  ...   
4               w         b          k           t  ...   
...           ...       ...        ...         ...  ...   
8119            c         b          y           e  ...   
8120            c         b          y           e  ...   
8121            c         b          n           e  ...   
8122            c         n          b           t  ...   
8123            c         b          y           e  ...   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat class  
0              o         p                 k          s       u     p  
1              o         p                 n          n       g     e  
2              o         p                 n          n       m     e  
3              o         p                 k          s       u     p  
4              o         e                 n          a       g     e  
...          ...       ...               ...        ...     ...   ...  
8119           o         p                 b          c       l     e  
8120           o         p                 b          v       l     e  
8121           o         p                 b          c       l     e  
8122           o         e                 w          v       l     p  
8123           o         p                 o          c       l     e  

[8124 rows x 23 columns]

In [4]:
x=df.drop(['class'],axis=1)
x

cap-shape cap-surface cap-color bruises odor gill-attachment  \
0            x           s         n       t    p               f   
1            x           s         y       t    a               f   
2            b           s         w       t    l               f   
3            x           y         w       t    p               f   
4            x           s         g       f    n               f   
...        ...         ...       ...     ...  ...             ...   
8119         k           s         n       f    n               a   
8120         x           s         n       f    n               a   
8121         f           s         n       f    n               a   
8122         k           y         n       f    y               f   
8123         x           s         n       f    n               a   

     gill-spacing gill-size gill-color stalk-shape  ...  \
0               c         n          k           e  ...   
1               c         b          k           e  ...   
2               c         b          n           e  ...   
3               c         n          n           e  ...   
4               w         b          k           t  ...   
...           ...       ...        ...         ...  ...   
8119            c         b          y           e  ...   
8120            c         b          y           e  ...   
8121            c         b          n           e  ...   
8122            c         n          b           t  ...   
8123            c         b          y           e  ...   

     stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
0                           s                      w                      w   
1                           s                      w                      w   
2                           s                      w                      w   
3                           s                      w                      w   
4                           s                      w                      w   
...                       ...                    ...                    ...   
8119                        s                      o                      o   
8120                        s                      o                      o   
8121                        s                      o                      o   
8122                        k                      w                      w   
8123                        s                      o                      o   

     veil-type veil-color ring-number ring-type spore-print-color population  \
0            p          w           o         p                 k          s   
1            p          w           o         p                 n          n   
2            p          w           o         p                 n          n   
3            p          w           o         p                 k          s   
4            p          w           o         e                 n          a   
...        ...        ...         ...       ...               ...        ...   
8119         p          o           o         p                 b          c   
8120         p          n           o         p                 b          v   
8121         p          o           o         p                 b          c   
8122         p          w           o         e                 w          v   
8123         p          o           o         p                 o          c   

     habitat  
0          u  
1          g  
2          m  
3          u  
4          g  
...      ...  
8119       l  
8120       l  
8121       l  
8122       l  
8123       l  

[8124 rows x 22 columns]

In [5]:
y=df['class']
y

0       p
1       e
2       e
3       p
4       e
       ..
8119    e
8120    e
8121    e
8122    p
8123    e
Name: class, Length: 8124, dtype: object

In [8]:
le=LabelEncoder()
x=x.apply(le.fit_transform)
x

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0             5            2          4        1     6                1   
1             5            2          9        1     0                1   
2             0            2          8        1     3                1   
3             5            3          8        1     6                1   
4             5            2          3        0     5                1   
...         ...          ...        ...      ...   ...              ...   
8119          3            2          4        0     5                0   
8120          5            2          4        0     5                0   
8121          2            2          4        0     5                0   
8122          3            3          4        0     8                1   
8123          5            2          4        0     5                0   

      gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0                0          1           4            0  ...   
1                0          0           4            0  ...   
2                0          0           5            0  ...   
3                0          1           5            0  ...   
4                1          0           4            1  ...   
...            ...        ...         ...          ...  ...   
8119             0          0          11            0  ...   
8120             0          0          11            0  ...   
8121             0          0           5            0  ...   
8122             0          1           0            1  ...   
8123             0          0          11            0  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 22 columns]

In [9]:
y=le.fit_transform(y)
y

array([1, 0, 0, ..., 0, 1, 0])

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [11]:
ml=svm.SVC()

In [12]:
ml.fit(x_train,y_train)

SVC()

In [13]:
pred=ml.predict(x_test)

In [14]:
pred

array([0, 1, 1, ..., 1, 0, 0])

In [15]:
ml.support_vectors_

array([[2., 2., 5., ..., 7., 5., 4.],
       [2., 0., 4., ..., 7., 4., 2.],
       [5., 2., 9., ..., 2., 3., 3.],
       ...,
       [0., 2., 8., ..., 5., 4., 3.],
       [0., 3., 4., ..., 7., 4., 0.],
       [5., 2., 8., ..., 3., 3., 0.]])

In [16]:
ml.support_

array([  26,   32,   34,   55,   69,   83,   86,   93,  102,  133,  137,
        142,  172,  179,  186,  206,  211,  261,  264,  287,  295,  307,
        334,  360,  373,  403,  406,  438,  451,  497,  501,  517,  524,
        529,  560,  563,  566,  588,  595,  597,  612,  631,  641,  657,
        686,  702,  711,  712,  730,  733,  734,  757,  779,  785,  807,
        837,  839,  845,  848,  854,  863,  901,  904,  918,  919,  922,
        939,  953,  973, 1006, 1050, 1051, 1067, 1072, 1120, 1123, 1124,
       1132, 1138, 1157, 1164, 1191, 1204, 1209, 1237, 1287, 1292, 1325,
       1347, 1350, 1374, 1376, 1399, 1407, 1410, 1425, 1461, 1477, 1483,
       1488, 1496, 1500, 1507, 1516, 1555, 1592, 1632, 1640, 1642, 1659,
       1685, 1701, 1724, 1737, 1759, 1773, 1787, 1865, 1921, 1934, 1942,
       1953, 2024, 2026, 2042, 2075, 2092, 2118, 2134, 2147, 2167, 2176,
       2192, 2198, 2205, 2215, 2232, 2234, 2245, 2272, 2303, 2327, 2353,
       2364, 2373, 2377, 2389, 2408, 2426, 2443, 24

In [17]:
ml.n_support_

array([364, 356])