In [1]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.svm import SVC 

In [2]:
df = pd.read_csv(r"C:\Users\shash\OneDrive\Desktop\mit\3rd sem\ml\OneDrive_1_15-8-2023\DATASETS-16AUG2023\golf_df.csv")
df

Outlook Temperature Humidity  Windy Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Outlook'] = le.fit_transform(df['Outlook'])
df['Temperature'] = le.fit_transform(df['Temperature'])
df['Humidity'] = le.fit_transform(df['Humidity'])
df['Windy'] = le.fit_transform(df['Windy'])
df['Play'] = le.fit_transform(df['Play'])

In [4]:
df

Outlook  Temperature  Humidity  Windy  Play
0         2            1         0      0     0
1         2            1         0      1     0
2         0            1         0      0     1
3         1            2         0      0     1
4         1            0         1      0     1
5         1            0         1      1     0
6         0            0         1      1     1
7         2            2         0      0     0
8         2            0         1      0     1
9         1            2         1      0     1
10        2            2         1      1     1
11        0            2         0      1     1
12        0            1         1      0     1
13        1            2         0      1     0

In [5]:
x = df.drop('Play',axis=1)
x

Outlook  Temperature  Humidity  Windy
0         2            1         0      0
1         2            1         0      1
2         0            1         0      0
3         1            2         0      0
4         1            0         1      0
5         1            0         1      1
6         0            0         1      1
7         2            2         0      0
8         2            0         1      0
9         1            2         1      0
10        2            2         1      1
11        0            2         0      1
12        0            1         1      0
13        1            2         0      1

In [6]:
y= df['Play']
y

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: Play, dtype: int32

In [7]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=30,test_size=0.2)

In [8]:
classifier = SVC()  
classifier.fit(x_train, y_train) 

SVC()

In [9]:
y_pred = classifier.predict(x_test)

In [10]:
print("Accuracy Score: ", accuracy_score(y_test,y_pred)*100)

Accuracy Score:  66.66666666666666


In [11]:
# get support vectors
classifier.support_vectors_

array([[2., 1., 0., 1.],
       [2., 2., 0., 0.],
       [1., 2., 0., 1.],
       [1., 0., 1., 1.],
       [2., 0., 1., 0.],
       [0., 0., 1., 1.],
       [2., 2., 1., 1.],
       [1., 2., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.]])

In [12]:
# get indices of support vectors
classifier.support_

array([ 3,  7,  9, 10,  0,  1,  2,  4,  6,  8])

In [13]:
# get number of support vectors for each class
classifier.n_support_

array([4, 6])

# 2nd iteration

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42,test_size=0.4)

In [15]:
classifier = SVC()  
classifier.fit(x_train, y_train)

SVC()

In [16]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 0, 1, 1, 1])

In [17]:
print("Accuracy Score: ", accuracy_score(y_test,y_pred)*100)

Accuracy Score:  83.33333333333334


In [18]:
# get support vectors
classifier.support_vectors_

array([[2., 1., 0., 1.],
       [1., 2., 0., 1.],
       [2., 2., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.],
       [2., 2., 1., 1.],
       [1., 2., 0., 0.],
       [0., 0., 1., 1.]])

In [19]:
# get indices of support vectors
classifier.support_

array([1, 2, 4, 0, 3, 5, 6, 7])

In [20]:
# get number of support vectors for each class
classifier.n_support_

array([3, 5])

# 3nd iteration

In [21]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=0,test_size=0.3)

In [22]:
classifier = SVC()  
classifier.fit(x_train, y_train)

SVC()

In [23]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 1])

In [24]:
print("Accuracy Score: ", accuracy_score(y_test,y_pred)*100)

Accuracy Score:  20.0


In [25]:
# get support vectors
classifier.support_vectors_

array([[1., 2., 0., 1.],
       [2., 1., 0., 1.],
       [2., 2., 0., 0.],
       [2., 1., 0., 0.],
       [1., 0., 1., 1.],
       [1., 2., 1., 0.],
       [2., 2., 1., 1.],
       [1., 2., 0., 0.],
       [0., 1., 1., 0.]])

In [26]:
# get indices of support vectors
classifier.support_

array([0, 2, 3, 6, 7, 1, 4, 5, 8])

In [27]:
# get number of support vectors for each class
classifier.n_support_

array([5, 4])