# PCA(principles components analysis)

In [76]:
import numpy as np
import pandas as pd

In [35]:
df=pd.read_csv(r"D:\mca_074\New folder\Book1.csv")

In [12]:
df

s      x     y
0      1  105.0  42.0
1      2  115.0  46.0
2      3  105.0  26.0
3      4   94.0  39.0
4      5   96.0  29.0
5      6  104.0  33.0
6      7  120.0  48.0
7      8  121.0  98.0
8      9  127.0  46.0
9     10   79.0  20.0
10  mean  106.6  42.7

In [60]:
x=df['x']
x

0     105.0
1     115.0
2     105.0
3      94.0
4      96.0
5     104.0
6     120.0
7     121.0
8     127.0
9      79.0
10    106.6
Name: x, dtype: float64

In [59]:
y=df['y']
y

0     42.0
1     46.0
2     26.0
3     39.0
4     29.0
5     33.0
6     48.0
7     98.0
8     46.0
9     20.0
10    42.7
Name: y, dtype: float64

In [64]:
cov=np.cov(x,y)
cov

array([[191.84, 183.38],
       [183.38, 419.81]])

In [67]:
eig_val,eig_vec=np.linalg.eig(cov)

In [68]:
print(eig_vec)
print(eig_val)

[[-0.87404447 -0.48584592]
 [ 0.48584592 -0.87404447]]
[ 89.90648615 521.74351385]


# up to here

In [70]:
xmean= x.mean()
xmean

106.6

In [71]:
xstd=x.std()
xstd

13.850631754544628

In [72]:
z = (x - xmean) / xstd
z

0    -0.115518
1     0.606471
2    -0.115518
3    -0.909706
4    -0.765308
5    -0.187717
6     0.967465
7     1.039664
8     1.472857
9    -1.992689
10    0.000000
Name: x, dtype: float64

In [51]:
data = np.array([
    [1, 2],
    [4, 5]])
data

array([[1, 2],
       [4, 5]])

In [54]:
evalues, evectors = np.linalg.eig(data)

In [56]:
evalues
evectors

array([[-0.80689822, -0.34372377],
       [ 0.59069049, -0.9390708 ]])

In [ ]:
from sklearn.tree import DecisionTreeRegressor 
from sklearn.tree import export_graphiz
regression= DecisionTreeRegression