In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv(r"C:\Users\shash\OneDrive\Desktop\mit\3rd sem\ml\OneDrive_1_15-8-2023\DATASETS-16AUG2023\weatherHistory.csv")
df.head()

Formatted Date        Summary Precip Type  Temperature (C)  \
0  2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain         9.472222   
1  2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain         9.355556   
2  2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain         9.377778   
3  2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain         8.288889   
4  2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                   251.0          15.8263         0.0               1015.13   
1                   259.0          15.8263         0.0               1015.63   
2                   204.0          14.9569         0.0               1015.94   
3                   269.0          15.8263         0.0               1016.41   
4                   259.0          15.8263         0.0               1016.51   

                       Daily Summary  
0  Partly cloudy throughout the day.  
1  Partly cloudy throughout the day.  
2  Partly cloudy throughout the day.  
3  Partly cloudy throughout the day.  
4  Partly cloudy throughout the day.

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Formatted Date            96453 non-null  object 
 1   Summary                   96453 non-null  object 
 2   Precip Type               95936 non-null  object 
 3   Temperature (C)           96453 non-null  float64
 4   Apparent Temperature (C)  96453 non-null  float64
 5   Humidity                  96453 non-null  float64
 6   Wind Speed (km/h)         96453 non-null  float64
 7   Wind Bearing (degrees)    96453 non-null  float64
 8   Visibility (km)           96453 non-null  float64
 9   Loud Cover                96453 non-null  float64
 10  Pressure (millibars)      96453 non-null  float64
 11  Daily Summary             96453 non-null  object 
dtypes: float64(8), object(4)
memory usage: 8.8+ MB


In [4]:
df.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [5]:
df.fillna(value = '0')

Formatted Date        Summary Precip Type  \
0      2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain   
1      2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain   
2      2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain   
3      2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain   
4      2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain   
...                              ...            ...         ...   
96448  2016-09-09 19:00:00.000 +0200  Partly Cloudy        rain   
96449  2016-09-09 20:00:00.000 +0200  Partly Cloudy        rain   
96450  2016-09-09 21:00:00.000 +0200  Partly Cloudy        rain   
96451  2016-09-09 22:00:00.000 +0200  Partly Cloudy        rain   
96452  2016-09-09 23:00:00.000 +0200  Partly Cloudy        rain   

       Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0             9.472222                  7.388889      0.89            14.1197   
1             9.355556                  7.227778      0.86            14.2646   
2             9.377778                  9.377778      0.89             3.9284   
3             8.288889                  5.944444      0.83            14.1036   
4             8.755556                  6.977778      0.83            11.0446   
...                ...                       ...       ...                ...   
96448        26.016667                 26.016667      0.43            10.9963   
96449        24.583333                 24.583333      0.48            10.0947   
96450        22.038889                 22.038889      0.56             8.9838   
96451        21.522222                 21.522222      0.60            10.5294   
96452        20.438889                 20.438889      0.61             5.8765   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
0                       251.0          15.8263         0.0   
1                       259.0          15.8263         0.0   
2                       204.0          14.9569         0.0   
3                       269.0          15.8263         0.0   
4                       259.0          15.8263         0.0   
...                       ...              ...         ...   
96448                    31.0          16.1000         0.0   
96449                    20.0          15.5526         0.0   
96450                    30.0          16.1000         0.0   
96451                    20.0          16.1000         0.0   
96452                    39.0          15.5204         0.0   

       Pressure (millibars)                           Daily Summary  
0                   1015.13       Partly cloudy throughout the day.  
1                   1015.63       Partly cloudy throughout the day.  
2                   1015.94       Partly cloudy throughout the day.  
3                   1016.41       Partly cloudy throughout the day.  
4                   1016.51       Partly cloudy throughout the day.  
...                     ...                                     ...  
96448               1014.36  Partly cloudy starting in the morning.  
96449               1015.16  Partly cloudy starting in the morning.  
96450               1015.66  Partly cloudy starting in the morning.  
96451               1015.95  Partly cloudy starting in the morning.  
96452               1016.16  Partly cloudy starting in the morning.  

[96453 rows x 12 columns]

In [6]:
df.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [20]:
le = LabelEncoder()
data_coloumns = ['Formatted Date' , 'Summary' , 'Precip Type' , 'Daily Summary']
for columns in data_coloumns:
    df[columns] = le.fit_transform(df[columns])
df.head() 

Formatted Date  Summary  Precip Type  Temperature (C)  \
0            2159       19            0         9.472222   
1            2160       19            0         9.355556   
2            2161       17            0         9.377778   
3            2162       19            0         8.288889   
4            2163       17            0         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                   251.0          15.8263         0.0               1015.13   
1                   259.0          15.8263         0.0               1015.63   
2                   204.0          14.9569         0.0               1015.94   
3                   269.0          15.8263         0.0               1016.41   
4                   259.0          15.8263         0.0               1016.51   

   Daily Summary  
0            197  
1            197  
2            197  
3            197  
4            197

In [8]:
#function for covariance matrix

def cova(df):
    
    #converting the dataframe into array for calculation
    data_array = df.to_numpy()
    
    #calculating mean
    mean = np.mean(data_array , axis = 0)
    
    #calculating the center point
    center = data_array - mean
    
    #calculating the covariance by multiplying it 
    cov_mat = np.dot(center.T , center) / (len(data_array) - 1)
    
    return cov_mat

cov_m = cova(df)
cov_m

array([[ 7.74710589e+08,  6.41658262e+03, -1.33279942e+02,
         8.14115679e+03,  9.28832551e+03,  2.41334807e+02,
        -2.54359797e+03, -8.17916088e+04,  1.16714003e+04,
         0.00000000e+00,  4.62002242e+04, -3.80813236e+04],
       [ 6.41658262e+03,  1.90226589e+01, -1.74301766e-01,
         6.10962629e+00,  6.66036210e+00, -9.64399525e-02,
         1.28399870e-01,  1.06734245e+01,  2.56227272e+00,
         0.00000000e+00,  7.31598249e+01,  3.86744082e+01],
       [-1.33279942e+02, -1.74301766e-01,  1.17670735e-01,
        -1.70501990e+00, -1.91459952e+00,  1.43715707e-02,
        -1.36211526e-01, -1.43554768e+00, -4.42111749e-01,
         0.00000000e+00,  5.01989824e-01, -4.67269144e+00],
       [ 8.14115679e+03,  6.10962629e+00, -1.70501990e+00,
         9.12320371e+01,  1.01418283e+02, -1.18046179e+00,
         5.91476036e-01,  3.07582353e+01,  1.57300713e+01,
         0.00000000e+00, -6.08574379e+00,  2.35904704e+02],
       [ 9.28832551e+03,  6.66036210e+00, -1.9145995

In [9]:
#getting the eigen values and eigen vectors
eigen_values , eigen_vectors = np.linalg.eig(cov_m)
print(eigen_values)
print(eigen_vectors)

[7.74710603e+08 1.36999556e+04 1.15282343e+04 3.18554178e+03
 1.64076881e+02 4.76335737e+01 1.80478874e+01 1.24710157e+01
 5.23800308e-01 1.86574805e-02 8.39676289e-02 0.00000000e+00]
[[ 9.99999991e-01 -6.43495781e-05  1.03699036e-04  4.41381496e-05
  -2.32620374e-05  4.50138740e-07 -9.61798188e-06  1.42709291e-05
   4.54191573e-08 -5.01018575e-07  1.23010657e-07  0.00000000e+00]
 [ 8.28255636e-06  5.34975291e-03  1.49912654e-03  1.16226555e-02
   3.15224591e-02  1.62839344e-02  9.92430197e-01  1.16693643e-01
  -5.51323735e-03  6.83367698e-04 -3.04119792e-03  0.00000000e+00]
 [-1.72037891e-07  3.23085618e-05 -1.40855379e-04 -1.54281961e-03
  -1.22356992e-02 -3.86878779e-03 -3.50624236e-03  8.88017896e-03
   3.49136418e-02  1.32258329e-01 -9.90469858e-01  0.00000000e+00]
 [ 1.05086260e-05 -5.28365345e-05  3.61080261e-03  7.83934974e-02
   6.57439397e-01  6.02754079e-02 -2.41018320e-02  4.66839454e-02
   7.44203633e-01  2.97985628e-02  2.22360679e-02  0.00000000e+00]
 [ 1.19893955e-05  4

In [13]:
data=pd.read_csv(r"C:\Users\shash\OneDrive\Desktop\mit\3rd sem\ml\OneDrive_1_15-8-2023\DATASETS-16AUG2023\play_tennis.csv")
data


day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [40]:
x=data['wind']
y=data['play']

In [41]:
le=LabelEncoder()
x=le.fit_transform(x)
x

array([1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0])

In [42]:
y=le.fit_transform(y)
y

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [44]:
xmean=x.mean()
xmean

0.5714285714285714

In [45]:
x.std()

0.4948716593053935

In [46]:
cov=np.cov(x,y)
cov

array([[0.26373626, 0.06593407],
       [0.06593407, 0.24725275]])

In [47]:
eigvalues,eigvectors=np.linalg.eig(cov)

In [51]:
eigvalues
eigvectors

array([[ 0.74967818, -0.66180256],
       [ 0.66180256,  0.74967818]])